### ISSUE TITLE
Error export to PDF

### ISSUE THREAD

**Issue by drcriado** [kriskbx/gitlab-time-tracker#17]
Hi kriskbx,

I've reproduced an error generating a report in pdf format.

![report_error](https://user-images.githubusercontent.com/31201886/29958361-c5b7e280-8ef2-11e7-9cb2-d5670a45f6f9.png)

Export function works correctly with other formats, except PDF. 

I use windows 10 x64 environment / node v6.11. I 've reproduced issue with nodejs command prompt, admin permissions, etc...

Thanks!

**Comment by kriskbx** [comment]
Hey!

Unfortunately I could not reproduce your issue. I tried it on a fresh Win10 x64 Pro, Node.js 6.11 setup, gtt installed via npm and yarn.

Are you using the latest (1.6.4) version of gtt? If not, please upgrade and try again. You should also try to remove gtt completely by using `npm -g remove gitlab-time-tracker` or `yarn global remove gitlab-time-tracker` and install it again to trigger the phantom.js build again.

If this doesn't help, please give me your GitLab username. I will grant you access to my testing project so we can rule out that this is an issue with an specific set of data.

**Comment by kriskbx** [comment]
I'm experiencing a similar issue now on Mac OSX. It seems like the markdownpdf suddenly package stopped working for whatever reason. I will look into it and hopefully get it fixed till the end of next week (sorry, busy with client projects right now).

Have you tried upgrading/reinstalling? Did it fix the problem?

**Comment by drcriado** [comment]
Sorry kriskbx, I'm too busy this week.

I tried reinstalling and I got an error, but it was different to previous.
![image](https://user-images.githubusercontent.com/31201886/30061068-3580f63c-9246-11e7-8279-287ba5175db1.png)

Regards!

**Comment by kriskbx** [comment]
Looks like you forgot the `--file` parameter. ;)

**Comment by kriskbx** [comment]
I just released version `1.6.6` which fixes the pdf bug for me on osx. Can you upgrade and try it again, please?

**Comment by drcriado** [comment]
It works!!

**Comment by swingbit** [comment]
I get the same issue with the docker image, version 1.7.40.

```
$ gtt --version
1.7.40
```

```
$ gtt report -c --url <url> --token <token> --from <from> --to <to> --output=pdf --file=output.pdf "grp/prj"
🔍  Selected projects: grp/prj
🔍  Resolving "grp/prj"... ✓
📦  Fetching issues... ✓
📦  Fetching merge requests... ✓
📎  Merging reports... ✓
⚙️️  Processing issues... ✓
📃  Making report... ✓
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: spawn /usr/local/share/.config/yarn/global/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
