### ISSUE TITLE
SyntaxError if run the command

### ISSUE THREAD

**Issue by rafanasiev** [kriskbx/gitlab-time-tracker#18]
➜  ~ gtt config
/usr/lib/node_modules/gitlab-time-tracker/gtt-config.js:6
let config = new Config(process.cwd());
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

**Comment by kriskbx** [comment]
What version of Node.js are you using? You can check that by running `node --version`. If your version of Node.js is less than 6.11 (I bet it's 5.* or something) make sure to upgrade Node.js to a more recent version (I recommend 8.4) and try again.

**Comment by rafanasiev** [comment]
➜  ~ node --version
v4.8.4

Thanks. Ok, let me try to upgrade it.

**Comment by kriskbx** [comment]
Did upgrading Node.js solved your problem?

**Comment by rafanasiev** [comment]
@kriskbx it seems to me - yes. But, I have to double check...

**Comment by kriskbx** [comment]
If it still fails, feel free to reopen the issue. :)
