### ISSUE TITLE
Using --subgroups when there are no subgroups does not properly return data

### ISSUE THREAD

**Issue by elboletaire** [kriskbx/gitlab-time-tracker#19]
I'm unable to get this working.. I've tried a lot of things, and I only get two errors:

- `Error: could not resolve "false"`
- `Error parsing configuration`

I installed the latest version using yarn, and I've gtt installed in yarn's default binary path. Using node version 6.11.3.

Here's my configuration file (located under ~/.gtt/config.yml):

~~~yaml
url: https://gitlab.cirici.com/api/v4/
token: MY_PRIVATE_TOKEN
~~~

Using that file, I only get the error `Error: could not resolve false`.

![imatge](https://user-images.githubusercontent.com/153305/30172653-c1e745d0-93f5-11e7-8d8d-f445bc1dc960.png)

If I create a `.gtt.yml` file in home with the following contents:

~~~yaml
url: https://gitlab.cirici.com/api/v4/
token: MY_PRIVATE_TOKEN
extend: false
~~~

Then rises the error `Error parsing configuration`...

![imatge](https://user-images.githubusercontent.com/153305/30172660-c7b8ab02-93f5-11e7-9d3b-046574656088.png)

What am I doing wrong¿?

**Comment by elboletaire** [comment]
OFC I've tried copy-pasting the entire config file described in the readme, but I get the same behavior.

**Comment by kriskbx** [comment]
You need to specify a project. Either in your config:
```yaml
project: "username/project-name"
```

... or on the command line.

```bash
gtt report "username/project-name"
```

I'm sorry that the error-message is not very helpful. I will work on this. Thanks for pointing this out. :)

**Comment by kriskbx** [comment]
Btw. you can specify [groups](https://github.com/kriskbx/gitlab-time-tracker#query-groups-and-subgroups) or [multiple projects/groups](https://github.com/kriskbx/gitlab-time-tracker#query-multiple-projects-or-groups-and-combine-the-data-in-one-report) too!

**Comment by kriskbx** [comment]
If you get the error `Error parsing configuration` you probably have a syntax error in your config file. YAML can be hard sometimes, especially with spaces. You can use an online YAML parser that shows more verbose errors: https://yaml-online-parser.appspot.com

**Comment by kriskbx** [comment]
I just pushed `1.6.7` which features more verbose error messages (and preview gifs, yay!)
Feel free to reopen the issue if you still need help. :)

**Comment by elboletaire** [comment]
I'm sorry but I'm unable to get it working...

![imatge](https://user-images.githubusercontent.com/153305/30212651-2049667a-94a6-11e7-815c-0ebd5a256581.png)

![imatge](https://user-images.githubusercontent.com/153305/30212660-29bf65d8-94a6-11e7-89b2-59efd30dce53.png)

~~~bash
gtt --version
1.6.7
~~~

😢

**Comment by kriskbx** [comment]
Hmm. This looks like a connection problem. Unfortunately gtt doesn't check that separately. So I pushed a new version that introduces the option `--check_token`.
Please update to `1.6.8` and try again with the above option to enable token checking up front: gtt should throw an error when the connection to GitLab itself fails (because of a wrong url, token or access rights). So we can rule out that this is an permission problem.

**Comment by elboletaire** [comment]
Thanks! Now it says `Invalid access token!`. I've created a token from my `/profile/personal_access_tokens` page giving it `api` and `read_user` privileges and I'm administrator of this gitlab installation.

What can be wrong? 😕

**Comment by elboletaire** [comment]
Oh, wait! I've two factor auth enabled in gitlab... I should disable it, right?

**Comment by elboletaire** [comment]
Errr.... I don't know what I done but now it's working (without ever disabling the 2fa), so you can close this issue.

Again, thanks for your patience!

**Comment by kriskbx** [comment]
No worries, you're welcome!

2FA should not be a problem: the personal access token is a different authentification system. I actually had to create a new access token in the past after a GitLab updat. So maybe the most recent update did something weird and your token didn't work until you refreshed that page? Dunno, just guessing here. Glad it worked out for you in the end. :)

**Comment by elboletaire** [comment]
BTW it works awesome! very good work @kriskbx 

If we see anything that could be improved we'll let you know 😉

**Comment by elboletaire** [comment]
> I actually had to create a new access token in the past after a GitLab updat.

Apparently is the same, because yesterday when I was trying this I also did a huge gitlab upgrade.

**Comment by elboletaire** [comment]
Sorry to bother you again, but there's something strange which I cannot figure out why is failing and I wouldn't like to open a new issue if it's not really necessary.

The thing is that I've checked getting reports for projects and groups without issues, except for one. 

We have a group named `club-metropolitan` with 5 projects inside. If I check for their projects one by one it returns the reports information:

![imatge](https://user-images.githubusercontent.com/153305/30219620-ef84b208-94bc-11e7-9791-88a90a309fd5.png)

but it does not work using `--type=group --subgroups`.

![imatge](https://user-images.githubusercontent.com/153305/30219602-de22a312-94bc-11e7-8df9-c58ed9a9e6bc.png)

Note that I've checked this in other groups and it works as expected:

![imatge](https://user-images.githubusercontent.com/153305/30219656-094aa116-94bd-11e7-99ac-f7c823d3b5f3.png)

Can you guess what's going on? Am I doing something wrong? I think that we renamed this project a long time ago; could it be related? I've been checking with other possible names without success :confused:

**Comment by kriskbx** [comment]
I need more information. Can you open this url in your browser (replace the abc with your actual token): `https://gitlab.cirici.com/api/v4/groups/?search=club-metropolitan?private_token=abc`
It should return JSON, and because you're using FF Dev-Edition it should be formatted as well. Pick the `id` of this group and open this url (replace the 123 with your id and abc with your token): `https://gitlab.cirici.com/api/v4/groups/123/projects?private_token=abc`. If there is confidential information in there feel free to obfuscate it or send it via mail to `m [at] kris [dot] cool`.

**Comment by elboletaire** [comment]
Yeah better send an e-mail, it's a lot of data and I've already said too much information 😄 

I've already sent it via `oscar [at] cirici [dot] com`.

**Comment by kriskbx** [comment]
So, we had an email conversation and it turns out that querying subgroups via `--subgroups` is doing weird stuff when there are no subgroups. Thanks again for pointing this out, I will fix this in a future release!

**Comment by elboletaire** [comment]
No, thank you @kriskbx, as said, you did a really great work with this package 😃

**Comment by kriskbx** [comment]
Thanks! You're welcome. Glad others can get some value from it. 😃

**Comment by kriskbx** [comment]
I just released version `1.6.9` including a fix for this issue.

**Comment by elboletaire** [comment]
I think there's still some kind of issue, at least with nested namespaces.

This works:

~~~bash
gtt report "alvarium/services/programmable-tv/app" --closed --user=oscar --from=2017-07-01 --hours_per_day=6
~~~

Whilst this does not:

~~~bash
gtt report "alvarium" --type=group --subgroups --closed --user=oscar --from=2017-07-01 --hours_per_day=6
~~~

For some reason, now it only retrieves part of the nested namespaces that the `alvarium` namespace has. Here's the `selected projects` string printed in the console:

    alvarium/demos/members-signup, alvarium/services/html2pdf, alvarium/documentation, alvarium/signup-docs, alvarium/web, alvarium/infrastructure/konga-deploy, alvarium/infrastructure/ansible-runner, alvarium/infrastructure/vault-deployment, alvarium/infrastructure/load-balancer, alvarium/infrastructure/rabbitmq-docker, alvarium/infrastructure/kong-docker

As you can see, there's only one project inside the `services` namespace, but we have more than 10 (all of them inside their own namespace each one).

Currently using `gtt` version 1.6.10

**Comment by kriskbx** [comment]
I was missing a recursive query for multilevel-subgroups. Just released version `1.6.11` which includes a fix for this. Please update and try again. :)

**Comment by elboletaire** [comment]
Nice! Now apparently works as expected 😃

**Comment by kriskbx** [comment]
I just release 1.7.0 including this fix.

**Comment by elboletaire** [comment]
Awesome @kriskbx, you're a machine! 😄
