### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by kkogovsek** [kriskbx/gitlab-time-tracker#20]
Hey, I have error at startup of your app. It's:

```
module.js:487
    throw err;
    ^
Error: Cannot find module '/home/klemen/.nvm/versions/node/v8.2.1/app.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by kriskbx** [comment]
Sorry, I need more information: What OS do you have? Have you installed gtt via npm or yarn? What version of npm/yarn are you using? What command have you typed in exactly?

**Comment by kkogovsek** [comment]
Hey Im using arch linux,
When i installed it globaly it didnt work (npm global or npx) then when I cloned repo it had troubles with access. Maby I can provide you with more info after K get to my PC or maby even create PR

**Comment by kriskbx** [comment]
What have you typed in and what was the output when you tried installing it globally? Did it succeed and running `gtt` gives you errors? If yes, please post the output here.

**Comment by kkogovsek** [comment]
Hey, sorry for delay. That was the output when running globally installed one. 
When running from source it gave permission denied error for folder creation in *src/include/file-config.js*. I poked around and deleted permissions when mkdir and then it worked.

**Comment by kriskbx** [comment]
This looks a lot like you've ran the installation with `sudo` or a different user the or you can't write to your own home directory.

Nevertheless, thanks for the issue: I will improve the error messages in a future release to make it clear, what's going on and what you have to do if you run into permission issues.
