### ISSUE TITLE
support http proxy parameter

### ISSUE THREAD

**Issue by jenghung** [kriskbx/gitlab-time-tracker#3]
It would be great if gitlab-time-tracker support http proxy by passing parameter to command line:
```sh
gtt report "kriskbx/example-project" --proxy=http://proxy.server.com:8080
```

**Comment by kriskbx** [comment]
Thanks for your feature request. I added proxy support with release [1.3.0](https://github.com/kriskbx/gitlab-time-tracker/releases/tag/1.3.0) which is out now. Make sure to upgrade via `npm -g install gitlab-time-tracker` or `yarn global upgrade gitlab-time-tracker` respectively.

You can use the option `--proxy="http://localhost:8888"` or add it to your config file: `proxy: http://localhost:8888`

Have fun and thanks for helping making gtt better.
