### ISSUE TITLE
Improve how namespaces are parsed

### ISSUE THREAD

**Issue by elboletaire** [kriskbx/gitlab-time-tracker#32]
Getting reports from a subset of namespaces works as expected, but when you try to grab an inner namespace, the way you have to call it differs from the real namespace and even from how they are displayed.

I better explain this with examples. Doing this:

~~~bash
gtt report "alvarium"
~~~

Returns the list of all the projects and namespaces inside `alvarium` namespace:

    🔍  Selected projects: alvarium/services/html2pdf, alvarium/demos/members-signup, alvarium/services/accounts/admin-widgets, alvarium/services/accounts/api, alvarium/services/activities/widgets, alvarium/services/activities/api, alvarium/infrastructure/konga-deploy, alvarium/infrastructure/ansible-runner, alvarium/infrastructure/vault-deployment, alvarium/infrastructure/load-balancer, alvarium/infrastructure/rabbitmq-docker, alvarium/infrastructure/kong-docker, alvarium/documentation, alvarium/signup-docs, alvarium/web, alvarium/services/auth/request-password-widget, alvarium/services/auth/api, alvarium/services/Emails/admin-widget, alvarium/services/Emails/api, alvarium/services/fees/fees-admin, alvarium/services/fees/fees-widget, alvarium/services/fees/api, alvarium/services/Helpdesk/helpdesk-widget, alvarium/services/Helpdesk/api, alvarium/services/OneRing/one-ring-electron, alvarium/services/OneRing/one-ring, alvarium/services/holidays/widgets, alvarium/services/holidays/api, alvarium/services/payments/callback-manager, alvarium/services/payments/client-example, alvarium/services/payments/api, alvarium/services/spreadsheets/api, alvarium/services/settings/settings-widget, alvarium/services/settings/settings-store, alvarium/services/members/migration-tool, alvarium/services/members/manager-api, alvarium/services/members/admin-widgets, alvarium/services/members/api, alvarium/services/programmable-tv/app, alvarium/services/programmable-tv/manager, alvarium/services/programmable-tv/api

Ok, now I want a report from the first one, `alvarium/services/html2pdf`:

![imatge](https://user-images.githubusercontent.com/153305/31336629-f72602e8-acf7-11e7-8f49-3df0e32e544d.png)

For this project I don't even know how to get a report only from it. On other cases I've been able to get reports, for example with the `alvarium/services/programmable-tv` namespace I can get reports using:

~~~bash
gtt report "programmable-tv" --type=group --closed
~~~

![imatge](https://user-images.githubusercontent.com/153305/31336902-3a240dd2-acf9-11e7-96ec-19c64a8b6d9d.png)

But I've a lot of projects named `app` or `api`, because we use namespaces to differentiate between projects, so I either know how to get a report from any of these subprojects. This are some of the commands I've tried so far:

- `gtt report "alvarium/programmable-tv/app"  --closed`
- `gtt report "alvarium/programmable-tv/app" --type=group  --closed`
- `gtt report "alvarium/programmable-tv/app" --type=group --subgroups  --closed`
- `gtt report "programmable-tv/app"  --closed`
- `gtt report "programmable-tv/app" --type=group  --closed`
- `gtt report "programmable-tv/app" --type=group --subgroups  --closed`

In all these cases I get a `Could not resolve "namespace/project"`.

So, the main issue here is that projects should be resolved as they're displayed. This means that trying to access `alvarium/services/programmable-tv/app` should be possible setting the entire set of namespaces as the project param.

I think gitlab internally does not store them that way, so I guess you should map them somehow.

**Comment by kriskbx** [comment]
Thanks for pointing this out. I was using the generic `path` instead of the `full_path` for searching groups. Can you pull the master branch and try again?

**Comment by elboletaire** [comment]
Yay! Now works as I was expecting! Awesome, thanks 😄 !!!

I left it open so you can close the issue when you need to (on tag creation, on merge, or whenever).

**Comment by kriskbx** [comment]
Thanks. I won't postpone 1.7.0 anymore, the release will be this week.

**Comment by kriskbx** [comment]
I just release 1.7.0 including this fix.
