### ISSUE TITLE
Trying to generate a report stops at "processing issues"

### ISSUE THREAD

**Issue by felixfoertsch** [kriskbx/gitlab-time-tracker#35]
```
$gtt -V
1.7.0
```

I am trying to set up gtt for a project on a gitlab instance hosted at our university. Reporting to an issue with `gtt start` works perfectly. I can report times to different issues as intended. So the basic configuration with the token should work.

However, generating reports gives the following error:

```
TypeError: Cannot read property 'total_time_spent' of undefined
    at resolve (/usr/local/share/.config/yarn/global/node_modules/gitlab-time-tracker/src/models/hasTimes.js:114:52)
    at Promise (<anonymous>)
    at promise.then (/usr/local/share/.config/yarn/global/node_modules/gitlab-time-tracker/src/models/hasTimes.js:107:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I tried using the yarn install first, then npm and then docker. The issue was the same with all three installations. The only settings in the global config are:

```
url:
token:  
closed: true
output: markdown
```

**Comment by felixfoertsch** [comment]
#34 I think?

**Comment by felixfoertsch** [comment]
Just tried it with 1.6.11. Reports work perfectly in 1.6.11.

**Comment by kriskbx** [comment]
Thanks for your patience. I just release version `1.7.1` which should fix this error. (Sorry, I can't reproduce it, that's why I have to guess here)

Please update and reopen the issue if you still have problems with it.

**Comment by felixfoertsch** [comment]
@kriskbx seems to be fixed! Thanks a lot! 👍

**Comment by kriskbx** [comment]
You're welcome :)
