### ISSUE TITLE
Filter from/to based on spent date

### ISSUE THREAD

**Issue by dlichtenegger** [kriskbx/gitlab-time-tracker#39]
Based on the output report it looks like the filtering is based on the date when the time tracking entry was created, not on the date when it was actually spent.

You can define the spent date directly with the short command:
`/spend 1h30m 2017-12-20`

This is a problem if you enter your time trackings not on the same day when they were actually spent.

**Comment by kriskbx** [comment]
Well, unfortunately you cannot define the date when using the API: https://docs.gitlab.com/ee/api/issues.html#add-spent-time-for-an-issue
You can't execute slash commands via the API either, so as far as I know there's no way of implementing this into gtt right now. I'm sorry. :(

**Comment by elboletaire** [comment]
@kriskbx what API call do you exactly use for getting the time tracking stats? This one?

    GET /projects/:id/issues/:issue_iid/time_stats

😕

**Comment by kriskbx** [comment]
There's no API endpoint for getting individual time records. The time stats endpoint only returns, well, stats... and this stats are not very helpful at all (https://docs.gitlab.com/ee/api/issues.html#get-time-tracking-stats). This is why I made gtt in the first place. Here's how it works: it queries all the issue comments and parses them for spend time. Take a look at the getTime method here to get an idea how it works: https://github.com/kriskbx/gitlab-time-tracker/blob/master/src/models/hasTimes.js#L74

**Comment by kriskbx** [comment]
I implemented filtering by actual dates in the latest release 1.7.5.
Submitting the date of your local time records to GitLab is still not possible.
