### ISSUE TITLE
Group names starting with a number are not resolved

### ISSUE THREAD

**Issue by spamsch** [kriskbx/gitlab-time-tracker#41]
When executing the following command

`gtt report 3dw --type=group`

then GTT does not seem to be able to resolve the group name yielding the following output

```
Selected projects: 
Resolving ""... ✓
Fetching issues... ✓
Fetching merge requests... ✓
Merging reports... ✓
Error: No issues or merge requests matched your criteria.
```

**Comment by spamsch** [comment]
Works for all other group names not starting with a number.

**Comment by kriskbx** [comment]
Thanks so much for reporting this issue and fixing it, I really appreciate it.
