### ISSUE TITLE
Show time records sorted by date

### ISSUE THREAD

**Issue by elboletaire** [kriskbx/gitlab-time-tracker#43]
When generating a report, the time records appear without order, which makes its analysis a bit hard.

![imatge](https://user-images.githubusercontent.com/153305/35384885-fbc53e4e-01c6-11e8-9984-f755d6280aef.png)

**Comment by kriskbx** [comment]
I just pushed new commits to the master branch that dort the records and issue table in descending order.

**Comment by kriskbx** [comment]
I just released version 1.7.4 which includes this. Feel free to reopen this issue if you still experience unsorted results.
