### ISSUE TITLE
Quick action to display today's entries

### ISSUE THREAD

**Issue by prismec** [kriskbx/gitlab-time-tracker#48]
`gtt report -u pri --today` would be great

**Comment by prismec** [comment]
Since there's no other way of adding comments on GitLab I will hijack this issue to say **thank you** for this great tool!

**Comment by kriskbx** [comment]
You're welcome. :smile: 

Shorthands `--today`, `--this_week` and `--this_month` will be implemented in the next version. I'll keep you up to date when it goes live.

**Comment by kriskbx** [comment]
I just released 1.7.5 which includes the shorthands mentioned above.
