### ISSUE TITLE
Bug in deserializing a frame

### ISSUE THREAD

**Issue by Svhorsch** [kriskbx/gitlab-time-tracker#50]
Hey there,
basically im doing a small UI for the gtt, and in some situations i have to edit the frame files automatically. After some tests i had the problem that gtt didn't recognizes the frame as current status anymore after editing it. 

This frame is recognized:
`
{
  "id" : "some-id",
  "project" : "a project",
  "resource" : {
    "id" : 148,
    "type" : "issue"
  },
  "notes" : [],
  "start" : "2018-05-17T12:45:00+02:00",
  "stop": false,
  "timezone" : "Europe/Berlin"
}
`

But this one isn't:
`
{
  "id" : "some-id",
  "project" : "a project",
  "resource" : {
    "id" : 148,
    "type" : "issue"
  },
  "notes" : [],
  "start" : "2018-05-17T12:45:00+02:00",
  "stop" : false,
  "timezone" : "Europe/Berlin"
}
`
See the difference? it took me a while to find that out, but the difference is the whitespace after "stop" before the ":", if its there, gtt fails to recognize it as current active. Just found out that even the whitespace after the ":" defines if its recognizeable, if its NOT there gtt fails again. (Other entities like start or notes... are not affected)

**Comment by Svhorsch** [comment]
Found the problem in tasks.js:
in line 141:
`Fs.find({"term": `"stop" ?: ?false`, "flags": "i"}, this.config.frameDir)`
should do the trick, so the whitespaces are ignored

**Comment by kriskbx** [comment]
Thanks for pointing this out. I just released 1.7.6 which fixes this error.

**Comment by Svhorsch** [comment]
nice, thank you!

**Comment by kriskbx** [comment]
You're welcome! <3
