### ISSUE TITLE
Not understandable Error parsing configuration error

### ISSUE THREAD

**Issue by Soullivaneuh** [kriskbx/gitlab-time-tracker#54]
```
$ cat .gtt.yml 
url: "https://git.vendor.net/api/v4"
token: "xXx"
project: "vendor/dat-project"
```

```
$ gtt report
Error parsing configuration: "/home/sullivan/projects/vendor/dat-project/.gtt.yml"
```

I did a scan of my Yaml file, the file is good.

I really don't see the issue here... :thinking: 

```
$ gtt --version
1.7.7
```

**Comment by Soullivaneuh** [comment]
Apparently, adding a `extend: false` on the file "solves" the issue.

But this was not obvious at all. Plus, I didn't edited any other config file.

**Comment by kriskbx** [comment]
Thank you for pointing this one out! The fix will be part of the next release. :)
