### ISSUE TITLE
New version 1.7.8: gtt stop not working any more

### ISSUE THREAD

**Issue by tom932** [kriskbx/gitlab-time-tracker#57]
@kriskbx thanks for the quick resolving of issue  56 (https://github.com/kriskbx/gitlab-time-tracker/issues/56).
However, I think you introduced a bug, which makes the tool unusable in that new version:
I updated to 1.7.8.
When I now start time tracking on an issue, it works as expected. However, when I try `gtt stop` I get the following error `Error: Error: Stop date is not in a valid ISO date format!`. 
I think the tool tries to parse the stop-date, which is `false` as a date. Now I have to write the date manually to the log file in order to get the tool to work again!

**Comment by kriskbx** [comment]
You're right. Sorry for that, this can happen from time to time if you don't have a proper test suite. I just released version 1.7.9 fixing this issue.
