### ISSUE TITLE
Allow pasting in preference dialog

### ISSUE THREAD

**Issue by daften** [kriskbx/gitlab-time-tracker#67]
Now pasting doesn't work (on Mac OS X), this would be handy for the access token and potentially also for the URL.
There also isn't a save button, but also nothing that shows the access token is actually valid, so a type can be very annoying.

**Comment by daften** [comment]
Wrong project, too many tabs open, my apologies :)

**Comment by kriskbx** [comment]
Haha, no worries. 😄
