### ISSUE TITLE
Error: could not fetch merge requests.

### ISSUE THREAD

**Issue by MendesJ** [kriskbx/gitlab-time-tracker#68]
Since last week (~2018-09-12), I can't export my time reports. I use the command below:

- gtt report "xxx" --type=group --subgroups --today --output=table --closed --user="yyy"

Computing report starts and then:

- Resolving "xxx" ... Check
- Fetching issues ... Check
- Fetching merge requests ...  Error: could not fetch merge requests.

I have refresh my token on gitlab but it has no effect. Before that it worked like a charm.

**Comment by kriskbx** [comment]
I need more information to debug this. Can you run the command again and provide a [dump](https://github.com/kriskbx/gitlab-time-tracker/blob/master/documentation.md#dumps) with your data via email: gtt at kris dot cool ? Please check your dump for sensitive information and black or delete it. Thank you!

**Comment by MendesJ** [comment]
Sorry but i can't send you the dump, I have checked it and a lot of data is sensitive.

I just can say that when the query below is executed, the body returned is empty. Also i'm not the only one having the issue all my teammates have the same problem. 

https://gitlab.com/api/v4/projects/XXXXXX/merge_requests?id=XXXXXX&order_by=created_at&page=1&per_page=100&private_token=YYYYYY&sort=desc&state=all.

I know it is difficult to debug with so few information, but if you have any other question don't hesitate to ask.

**Comment by kriskbx** [comment]
I tried this a couple of times with my test setup and I cannot replicate it, I'm sorry. Does the error occur within a project of a subgroup? Can you run it with the `--verbose` flag and see if the error message is more specific then?

**Comment by kriskbx** [comment]
As this is older than 2 months I will close this for now. If you need further help feel free to reopen the issue.
