### ISSUE TITLE
Gtt report output to xlsx format and time_format as seconds, cells are still string

### ISSUE THREAD

**Issue by daften** [kriskbx/gitlab-time-tracker#70]
When you want to use the report data in excel, I'd expect numeric data to be a number formatted cell in excel, so I can e.g. use autosum.
At the moment when outputting time_format as --time_format="[%seconds_overall]", the output cells are strings and summing a column e.g. with a condition on a certain user, gives me 0 as the total. I could easily create custom reports with totals by user based on the records sheet, if the numbers data was actual numbers. Can this be changed?

**Comment by cgdobre** [comment]
Thanks for this incentive to get me to overcome my laziness of formatting the cells :)

Yes, I'm sure it's possible, I just made the simplest possible implementation and preferred due to the reason above to just correct the cell type from excel directly.

I'll try to get a PR in during the weekend.

**Comment by kriskbx** [comment]
Thanks a lot @cgdobre ! Looking forward to merge it :)

**Comment by daften** [comment]
Awesome, thanks @cgdobre and @kriskbx  :)
