### ISSUE TITLE
Cannot process issues

### ISSUE THREAD

**Issue by fbsanchez** [kriskbx/gitlab-time-tracker#73]
Since last gitlab update, I've been unable to create a report for a project. The tool says 'Error: Cannot process issues' and dies

**Comment by kriskbx** [comment]
Can run the command again with the `--verbose` argument and paste the error message in here?

**Comment by alain-andre** [comment]
I'm having the same issue. using `--verbose` it reveal a `StatusCodeError: 429` with the following message : `Too many requests received`

The project is only 481 issues, any idea on how to fix this ?
