### ISSUE TITLE
Version is reported incorrectly for 1.7.31

### ISSUE THREAD

**Issue by daften** [kriskbx/gitlab-time-tracker#74]
It is still reported as 1.7.30, probably because gtt.js isn't updated. The strange thing is that the code here still says 1.7.29 :s 
![screen shot 2018-10-11 at 18 36 38](https://user-images.githubusercontent.com/1221024/46819666-9d1b7680-cd84-11e8-8a9d-c859c4c0932d.png)

**Comment by kriskbx** [comment]
Thanks for pointing this out!
