### ISSUE TITLE
Token permissions not clarified in doc

### ISSUE THREAD

**Issue by glensc** [kriskbx/gitlab-time-tracker#78]
doc says:

> Add your GitLab API url and your GitLab API personal token to the config file and save it afterwards.

but what permissions (scopes) should be given to the token. these not mentioned in the doc.

![image](https://user-images.githubusercontent.com/199095/47009655-bdad4d00-d145-11e8-920b-d8c300df6930.png)

**Comment by fboutin-pmc** [comment]
The ` api` permission suffice.

**Comment by glensc** [comment]
the issue was not about question, but rather that documentation is missing. so should not be closed just because fboutin-pmc replied.

**Comment by kriskbx** [comment]
I updated the docs in case you missed it.

**Comment by glensc** [comment]
indeed. next time include `#78` in commit message, of if forget leave commit hash in comment.

**Comment by kriskbx** [comment]
Next time, you could say something like "thank you" or "please" or just show any type of appreciation for a piece of software I put hundreds of unpaid hours into and you can use for free. You're not in the place to complain how I should do stuff here. Yeah, you can ask for it - that's fine. And you might be right, I should have mentioned this issue. But this behavior is very discouraging.
