### ISSUE TITLE
wrong path on windows

### ISSUE THREAD

**Issue by swiffer** [kriskbx/gitlab-time-tracker#84]
The path seems not to be created correctly.

Error: ENOENT: no such file or directory, mkdir 'C:\Users\USERACC\.local\share\.gtt'

**Comment by AlejoFab** [comment]
+1

**Comment by kriskbx** [comment]
Thanks for pointing out. Seems like the mkdir recursive option doesn't work on Windows. So I switched to shell.js. Make sure to update to `1.7.39` which should fix this issue.

**Comment by swiffer** [comment]
@kriskbx thanks!!! from the docs the path should be slightly different on windows:

**Comment by kriskbx** [comment]
You're right. The docs are out of date and I will fix that soon.
